server <- function(input, output, session) {
  observe_helpers()
  callModule(rancanganPercobaan, "rancangan")
  callModule(performaPanelis, "performa")
  callModule(metodeQda, "qda")
  callModule(metodeCata, "cata")
  callModule(metodeRata, "rata")
  callModule(metodeRata2, "rata_as_cata")
  callModule(metodeFcp, "fcp")
  callModule(metodeFp, "fp")
  callModule(metodeSorting, "sorting")
  callModule(metodeNapping, "napping")
  callModule(metodeJar, "jar")
  callModule(ujiDiskriminasi, "diskriminasi")
  callModule(acceptanceTest, "acceptance")
  callModule(pairedPreference, "pairedpref")
  callModule(multpairedPreference, "multpref")
  callModule(preferenceRanking, "prefrank")
  callModule(hedonicRating, "hedonic")
}
